//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseProject.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskId { get; set; }
        public int ProjectId { get; set; }
        public int ExecutorId { get; set; }
        public int StatusId { get; set; }
        public int RoleId { get; set; }
        public System.DateTime PeriodStart { get; set; }
        public System.DateTime PeriodEnd { get; set; }
        public int Priority { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Status Status { get; set; }
        public virtual TaskRole TaskRole { get; set; }
        public virtual User User { get; set; }
    }
}
